---
- name: Include Node.js tasks for Debian/Ubuntu
  ansible.builtin.include_tasks: nodejs-debian.yml
  when: ansible_os_family == 'Debian'

- name: Include Node.js tasks for RedHat/Fedora
  ansible.builtin.include_tasks: nodejs-redhat.yml
  when: ansible_os_family == 'RedHat'
